Repository jaimeenahn/goHomeBulls, pull requests merged in 2018-05, with the labels that each got.

#158 [Enhancement from 115] Accept Uppercases and restart after death
  Team meeting/Minutesofteammeeting2018-04-19.txt
  Team meeting/Minutesofteammeeting2018-04-26.txt
  scene/scene_editor.js
  scene/scene_main.js
  scene/scene_title.js
Labels: enhancement, official release

#161 Modified refresh function
  scene/scene_main.js
Labels: enhancement, official release

#168 Enhancement(uppercase and reset when lack of stamina)
  scene/scene_main.js
  stamina.js
Labels: CSE115, enhancement, official release

#172 Merge to master
  goHomeBulls.html
  scene/scene_editor.js
  scene/scene_main.js
  stamina.js
Labels: official release

#186 Add background for stamina shop
  StaminaShop.html
  goHomeBulls.html
  images/06.jpg
  images/eg_bg_06.gif
Labels: Feature request

#195 Official release README update
  README.md
  Team meeting/Minutesofteammeeting2018-05-03.txt
Labels: official release
